dtrugman/pfs

- include/pfs/task.hpp
- include/pfs/utils.hpp
- sample/enum_fd.cpp
- src/task.cpp
- src/utils.cpp
The current get_fds() API allows obtaining the process's number
of opened file descriptors, however, it forces saving extra temporary
information. The new count_fds() API could be useful in case of
processes with a large number of fds (ex: massive fd leakage).
> Add count_fds() API as part of the task API

- include/pfs/task.hpp
- include/pfs/utils.hpp
- src/task.cpp
- src/utils.cpp
- Allow resolution of a single namespace inode.
- Use stat for resolution (instead of readlinkat) to avoid string
parsing and optimize access.
> Refactor namespace inode resolution

- include/pfs/types.hpp
- sample/format.hpp
- src/parsers/uptime.cpp
- test/uptime.cpp
Upgrade the uptime struct to hold steady_clock::duration instead
of doubles for time values.
> Use steady_clock::duration instead of double in uptime

- include/pfs/mem.hpp
- src/mem.cpp
This fixes #13 
Modules that included mem.hpp encountered an error: `loff_t` type is unknown
Because the relevant include was included from the source file.
> Fix unknown type loff_t

- README.md
- include/pfs/task.hpp
- src/task.cpp
Allow users of the library access both process-global and
thread-specific parameters.
See README for more information.
> Allow thread specific access

- include/pfs/types.hpp
- sample/format.hpp
- src/parsers/status.cpp
- test/status.cpp
When running inside containers, these include multiple values,
one for every namespace.
We should parse a list out of this value.
> Fix task status ns_xxxx type and parsing

- include/pfs/net.hpp
- include/pfs/parsers.hpp
- include/pfs/types.hpp
- sample/enum_net.cpp
- sample/format.hpp
- src/net.cpp
- src/parsers/net_device.cpp
- test/net_device.cpp
Use pfs to get network device information from `/proc/net/dev`.  Adds parser, unit test, and sample out for new parser.
> Add parser for /proc/net/dev

- CMakeLists.txt
- README.md
Avoid possible option collisions when using pfs as sub-directory. Some options are supposed to be shared with the project and are common CMake flags, like the `CMAKE_BUILD_TYPE` or `BUILD_SHARED_LIBS`. Whereas other flags are not supposed to be shared, and hence should are to be prefixed with the project name.
While at it, print all CMake options while building to ease debugging and standardize the formatting of the `CMakeLists.txt` file.
> Adjust to compilation as CMake sub-directory

- docker/Dockerfile-redhat
- docker/Dockerfile-ubuntu
- docker/docker-pfs
Create a number of Docker spec files that allow users to develop, test and evaluate pfs on a range of Linux distros with minimal fuss.
> Add docker images for easier compilation and evaluation

- include/pfs/net.hpp
- include/pfs/parsers.hpp
- include/pfs/types.hpp
- include/pfs/utils.hpp
- sample/enum_net.cpp
- sample/format.hpp
- src/net.cpp
- src/parsers/net_socket.cpp
- src/parsers/route.cpp
- src/utils.cpp
- test/route.cpp
Working on a parser for IPv6 as well (it's a different file called `/proc/net/ipv6_route`)
Use pfs to get network device information from `/proc/net/route`. Adds parser, unit test, and sample out for new parser.
> Add Parser for /proc/net/route

- CMakeLists.txt
- cmake/pfs-config.cmake.in
Adds a CMake configuration file to make it possible for CMake-based projects to use `find_package` to consume this library.
> cmake: support find_package(pfs)

- src/task.cpp
- test/task_stat.cpp
- test/test_utils.hpp
Although in man page:
https://man7.org/linux/man-pages/man5/proc.5.html
The comm field has a description: `Strings longer than TASK_COMM_LEN (16) characters (including the terminating null byte) are silently truncated.` However, if you check the kernel code in fs/proc/array.c,(https://elixir.bootlin.com/linux/v6.4.1/source/fs/proc/array.c#L99) you will find that the description is only valid in the `__get_task_comm(tcomm, sizeof(tcomm), p);` branch of `proc_task_name` function. The actual maximum length is 64 instead. Hence, we are seeing pfs isn't reflecting all the `/proc/pid/stat` comm field correctly. Hence the change and the added tests.
> fix comm field in /proc/pid/stat

- CMakeLists.txt
Use `PROJECT_NAME` instead of `CMAKE_PROJECT_NAME` so that `pfs` can be
used as a submodule from a different top-level project.
> Fix `PACKAGE_CONFIG` naming.

- include/pfs/parsers/common.hpp
- src/block.cpp
- src/parsers/common.cpp
- src/parsers/maps.cpp
- src/parsers/mountinfo.cpp
- test/test_common.cpp
- test/test_maps.cpp
- test/test_mountinfo.cpp
- test/test_utils.hpp
The device number (major:minor) is being represented in different bases across different sources:
- procfs `maps`: hexadecimal 
- procfs `mountinfo`: decimal 
- sysfs `block/dev`: decimal  
This commit handles parsing of these different representations.
Changes:
- Explicitly setting the wanted base for each parsing flow
- Added UT case to cover the new functionality
> Device number parsing: Handle decimal/hexadecimal representations

- CMakeLists.txt
Hi,
The include directory was not being set anywhere so the CMake find_package did not set any `INCLUDE_DIR` variables. I have fixed this so it uses the `target_` include directory functions and sets it directly on the target, which means the include directories are set when you use the `target_link_library` call.
> fix: set target_include_directory

- CMakeLists.txt
- include/pfs/task.hpp
- sample/enum_net.cpp
- src/task.cpp
- test/test_proc_stat.cpp
Allow the user to specify their desired CMAKE_CXX_STANDARD and CMAKE_CXX_EXTENSIONS.
> Remove explicit --std=c++11 compile-option

- include/pfs/types.hpp
- src/parsers/buddyinfo.cpp
- test/test_buddyinfo.cpp
The number of chunks, and therefore the number of columns, in `/proc/buddyinfo` is dependent on the value of the `MAX_ORDER` macro, defined in [`linux/mmzone.h`](https://github.com/torvalds/linux/blob/v6.12/include/linux/mmzone.h#L30), which can be configured at compile time with the `CONFIG_ARCH_FORCE_MAX_ORDER` option. These changes modify the buddyinfo parser to allow for any number of chunks.
> Account For Variable Columns In `/proc/buddyinfo`

- CMakeLists.txt
Required follow up of #47 so that the package can be used from an install space.
> fix(package.xml): install ROS package xml file

- src/parsers/mountinfo.cpp
C++20 deprecates this:
```cpp
enum { foo = /* whatever */ };
enum { bar = /* whatever */ };
auto baz = foo + bar;
```
Which produces the warning `arithmetic between different enumeration types`, which is turned into an error with the `-Werror` flag.
> fix: arithmetic between different enumeration types

- src/procfs.cpp
Fixes issue #56
This fixes compilation with clang using "stdlib=libc++ std=c++23"
Without the change compilation fails:
```
pfs/src/procfs.cpp:129:42: error: no member named 'inserter' in namespace 'std'
129 |     parsers::parse_file_lines(path, std::inserter(output, output.begin()),
|                                     ~~~~~^
pfs/src/procfs.cpp:140:42: error: no member named 'inserter' in namespace 'std'
140 |     parsers::parse_file_lines(path, std::inserter(output, output.begin()),
|                                     ~~~~~^
```
> fix: no member named 'inserter'

- include/pfs/task.hpp
- src/task.cpp
Implements #58 
Enables reading Audit Login Session ID of a task (https://www.kernel.org/doc/Documentation/ABI/stable/procfs-audit_loginuid)
> add function to read task audit session id

- include/pfs/types.hpp
- src/parsers/unix_socket.cpp
- test/test_unix_socket.cpp
qmux socket paths might have an extra number at the end of the line:
```
// cad3ab00:         00000003 00000000 00000000 0001 03 7242 /var/qmux_client_socket    401
```
Make sure the parser handles that correctly.
> Support qmux socket paths

- docker/Dockerfile-debian12-32bit
- include/pfs/task.hpp
- include/pfs/types.hpp
- include/pfs/utils.hpp
- sample/enum_fd.cpp
- src/parsers/maps.cpp
- src/task.cpp
- src/utils.cpp
- test/test_maps.cpp
When compiling into a 32-bit binary and running on a 64-bit system, the process should be able to represent the entire memory space.
Hence, use 64bit variables instead of the system native ones.
> Use 64 bit types instead of ino_t and size_t
